name: Run Footium Listings Script (ending in 2)

on:
  schedule:
    # Run the script every 10 minutes at xx:02, xx:12, xx:22, etc.
    - cron: '2,12,22,32,42,52 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Set Git user identity
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Run Footium listings script
        run: |
          python SmallFoot.py
        env:
          OPENSEA_API_KEY: ${{ secrets.OPENSEA_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Commit and push changes
        run: |
          git add footium_clubs_listings.csv
          git commit -m "Update CSV with new listings"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
