name: Run Footium Listings Script

on:
  schedule:
    # Run the script every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Footium listings script
        run: |
          python SmallFoot.py

      - name: Commit and push changes
        run: |
          git add footium_clubs_listings.csv
          git commit -m "Update CSV with new listings"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
