name: Run Footium Listings Script

on:
  schedule:
    # Run the script every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Set up Git for committing changes
        run: |
          git config --global user.email ${{ secrets.GITHUB_EMAIL }}
          git config --global user.name ${{ secrets.GITHUB_USERNAME }}

      - name: Run Footium listings script
        run: |
          python SmallFoot.py

      - name: Push changes to the repository
        run: |
          git add footium_clubs_listings.csv
          git commit -m "Update CSV with new listings"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This is automatically provided by GitHub Actions
